### ISSUE TITLE
Initial AirPal Setup

### ISSUE THREAD

**Issue by marianna0702** [marianna0702/AirPal#1]
Current Status: 

- General setup of view and view model
- Implemented API communication (https://aviationstack.com/)

Next Steps:
- Rough implementation of text service

**Comment by peterkos** [comment]
Woo!
Quick suggestion:
```
## AC
- Create [which views do you wanna create]
- Implement AvationStack API for:
  - [specific calls you want to make: "fetch flight id/name/info"]
  // ^^ can be generic and change once you go to implement,
  //    helps to not over-implement a million things
```

I'd suggest splitting the view/viewmodel and connecting the API as two separate issues -- prevents coupling those layers together accidentally and getting overwhelmed in new files/classes

**Comment by marianna0702** [comment]
Great suggestions. I like using issues as upcoming tickets or tasks and defining the goal there.
